### ISSUE TITLE
Ending turn when player has 0 initiative

### ISSUE THREAD

**Issue by kapselccc** [esoviscode/discord-bot#112]

**Comment by Silentsky0** [comment]
We agreed that a player could do some changes in his inventory when his action points have depleted, closing

**Comment by kapselccc** [comment]
He could do that but that's not in his turn. The round should carry on with the other players actions, and player should be able to change his inventory  between his turns.

**Comment by Silentsky0** [comment]
The player's round ending abruptly is illogical and would impair UX
