### ISSUE TITLE
Use IP to database not in code

### ISSUE THREAD

**Issue by Mixss** [esoviscode/discord-bot#25]

**Comment by Silentsky0** [comment]
@Mixss this has already been implemented:

https://github.com/esoviscode/discord-bot/blob/8a4107242acdab7258f3ebb0f0146d10f51c1dc7/dnd-bot/dnd_bot/database/database_connection.py#L23-L38

environment variables can be provided directly from the terminal:
```
BOT_TOKEN=1234 python3 main.py
```

or via an anv file - when using a docker image
